user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    upstream emqx_tcp_cluster {
        server emqx1:1883;
        server emqx2:1883;
    }

    server {
        listen 1883;
        proxy_pass emqx_tcp_cluster;
        proxy_buffer_size 4k;
    }
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream emqx_http_dashboard {
        server emqx1:18083;
        server emqx2:18083;
    }

    server {
        listen 80;
        
        # OTA updates
        location /ota/ {
            proxy_pass http://centralcontroller:80/ota/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 18083;

        location / {
            proxy_pass http://emqx_http_dashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
